### ISSUE TITLE
No such module 'MapboxMaps' when using $RNMapboxMapsImpl = 'mapbox' 

### ISSUE THREAD

**Issue by afouadm** [rnmapbox/maps#1851]
**Describe the bug**  
The project builds fine when following the instructions but once I add  the below two lines to the PodFile, the build fails with the error No such module 'MapboxMaps', the error is in the rnmapbox-maps pod
```
$RNMapboxMapsImpl = 'mapbox'
$RNMapboxMapsVersion = '~> 10.4.3'
```

**To Reproduce**  

1. Initial Setup

```
react-native init MapBoxTest --template react-native-template-typescript
npm install rnmapbox/maps#main --save
```
2. Perform the token setup as described in [this guide](https://docs.mapbox.com/ios/maps/guides/install/#configure-credentials)
3. Add the below two line to the PodFile
```
$RNMapboxMapsImpl = 'mapbox'
$RNMapboxMapsVersion = '~> 10.4.3'
```
4. pod install
5. build

Below are the package.json and PodFile for a project I tried to spawn just to test this issue and it is suffering from the same issue

package.json
```
{
  "name": "mapboxtest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.68.1",
    "@rnmapbox/maps": "github:rnmapbox/maps#main"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.67.3",
    "@types/react-test-renderer": "^17.0.1",
    "@typescript-eslint/eslint-plugin": "^5.17.0",
    "@typescript-eslint/parser": "^5.17.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.4.4"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

```

PodFile

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'MapBoxTest' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MapBoxTestTests' do
    inherit! :complete
    # Pods for testing
  end
  #use_frameworks!
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()
  pod 'MapboxMaps', '10.4.3' 
  $RNMapboxMapsImpl = 'mapbox'
  $RNMapboxMapsVersion = '~> 10.4.3'

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    $RNMapboxMaps.post_install(installer)
  end
end

```

I manually added the line "pod 'MapboxMaps', '10.4.3'" to try to fix the issue, but still it didn't fix my issue

**Expected behavior**  
A succesful build

**Actual behavior**  
Build fails with "No such module 'MapboxMaps'" error

**Versions:**  
 - Platform: [iOS]
 - Platform OS: [Building for iOS 13]
 - Device: [Does not reach the run phase]
 - Emulator/ Simulator: [Does not reach the run phase]
 - Dev OS: [macOS with M1 chip]
 - @rnmapbox/maps Version [10.0.0-beta.1]
 - Mapbox GL version [5.12.1]
 - React Native Version [0.68.0]

**Additional context**

- Works fine on Android
- I tried to manually add the dependencies as described in [this MapBox official guide](https://docs.mapbox.com/ios/maps/guides/install/#configure-credentials) but this didn't change anything
- I tried to use use_frameworks! as described in the above guide but this leaded to different errors in other packages and didn't fix my problem.

Here is a screenshot of rnmapbox-maps pod dependency

![Screen Shot 2022-04-19 at 11 39 57 AM](https://user-images.githubusercontent.com/6014128/163893773-49f5ab92-c342-4575-bbfa-af96fe313923.png)

**Comment by kayro2222** [comment]
Use the `8.5.0` version.

**Comment by afouadm** [comment]
> 

Does the 8.5.0 version support $RNMapboxMapsImpl = 'mapbox' ?

**Comment by kayro2222** [comment]
> > 
> 
> Does the ```8.5.0``` version support ```$RNMapboxMapsImpl = 'mapbox'``` ?

The version that you are trying to use isn't fully released. Change the version on your package to 8.5.0.

**Comment by afouadm** [comment]
I want support for the mapbox implementation not the maplibre implementation, does 8.5.0 support it?

**Comment by kayro2222** [comment]
> I want support for the mapbox implementation not the maplibre implementation, does 8.5.0 support it?

feel free to test it and read the docs.

**Comment by SikoraKam** [comment]
If I use previous versions (also 8.5 as you mentioned) I get errors linked here https://github.com/rnmapbox/maps/pull/1571, where community suggest to use maplibre instead (yeah, very helpful).
I tried 8.5 both with Mapbox-gl and Mapbox and still the same

**Comment by kayro2222** [comment]
You are doing something wrong. I have a app in production running with
mapbox implementation with 8.5.0.

Em qui., 21 de abr. de 2022 11:21, Kamil Sikora ***@***.***>
escreveu:

**Comment by kayro2222** [comment]
> If I use previous versions (also 8.5 as you mentioned) I get errors linked here https://github.com/rnmapbox/maps/pull/1571, where community suggest to use maplibre instead (yeah, very helpful).
> I tried 8.5 both with Mapbox-gl and Mapbox and still the same 

8.5.0 is the latest version. See the repository tags to check the last stable version of the repo. I think you error is happening because you are using packages not compatibles. Did you see if v10 mapbox is compatible with rnmapbox 8.5.0?

**Comment by SikoraKam** [comment]
I tried mapbox and mapbox-gl so at least the second should be. Could you share your podfile and write which exactly version you have in your package.json?

**Comment by ahardy42** [comment]
the instructions for the fully released version are in the [v8 branch](https://github.com/rnmapbox/maps/tree/v8)

```
  pre_install do |installer|
    $RNMBGL.pre_install(installer)
    ... other pre install hooks
  end
```
and 
```
  post_install do |installer|
    $RNMBGL.post_install(installer)
    ... other post install hooks
  end
```
for the Podfile changes. you can use a custom version of mapbox SDK with 
```
$ReactNativeMapboxGLIOSVersion = '~> 6.1' # whichever version you'd like to use
```

**Comment by afouadm** [comment]
@ahardy42 Thanks a lot for pointing me out for this version, it works now

@SikoraKam I followed the iOS installation instructions and it worked fine, the only point is that the installation document will point you to the Mapbox site to find the latest version of sdk which is currently 10.4.3, but this won't work with 8.5.0, y you will need to use ```$ReactNativeMapboxGLIOSVersion = '~> 6.4.1'```

**Comment by SikoraKam** [comment]
Guys, one more question, Did anybody build that on MacBook with M1? If I install version from v8 branch and follow their instructions (and also what @afouadm suggested) I get errors about architecture arm64

❌  Undefined symbols for architecture arm64
┌─ Symbol: _OBJC_CLASS_$_MGLAccountManager
└─ Referenced from: objc-class-ref in libreact-native-mapbox-gl.a(MGLModule.o)
❌  ld: symbol(s) not found for architecture arm64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

@afouadm @ahardy42

**Comment by ahardy42** [comment]
@SikoraKam I'm not seeing errors building from an M1 air. using the following versions:

```$ReactNativeMapboxGLIOSVersion = '~> 6.1'```
and
```"@react-native-mapbox-gl/maps": "^8.6.0-beta.0"```

**Comment by afouadm** [comment]
> Guys, one more question, Did anybody build that on MacBook with M1? If I install version from v8 branch and follow their instructions (and also what @afouadm suggested) I get errors about architecture arm64
> 
> ❌ Undefined symbols for architecture arm64 ┌─ Symbol: _OBJC_CLASS_$_MGLAccountManager └─ Referenced from: objc-class-ref in libreact-native-mapbox-gl.a(MGLModule.o) ❌ ld: symbol(s) not found for architecture arm64
> 
> ❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> @afouadm @ahardy42
> 
> That's why I resigned from 8.5 version and I tried ti implement it with v10 branch and their instructions for using Mapbox-gl instead of maplibre

@SikoraKam I am working on M1 too, using ```"@react-native-mapbox-gl/maps": "^8.5.0"``` and ```$ReactNativeMapboxGLIOSVersion = '~> 6.4.1'```

Those errors might be because of messed up environment from previous builds, try to do ```pod deintegrate``` delete the DerivedData folder and do ```pod install``` again

**Comment by Rubenvdveen** [comment]
@afouadm @ahardy42 I am also experiencing the exact same issue as @SikoraKam . I've tried deleting podfile.lock, running `pod deintegrate` and deleting DerivedData. The error still occurs. 
```
Undefined symbol: _OBJC_CLASS_$_MGLAccountManager
```

My environment seems to be the same as yours @afouadm , running on M1 mac with `"@react-native-mapbox-gl/maps": "^8.5.0"` and `$ReactNativeMapboxGLIOSVersion = '~> 6.4.1'`. Though, I also had to check `For install builds only` in `[CP] Embed Pods Frameworks` to avoid getting the error: `Multiple commands produce Mapbox.frameworks`. That might help?

Any idea what could be wrong? I'm happy to share more information about my environment if needed.
