### PR TITLE
Add RNMapboxMapsImpl to expo plugin

### PR DESCRIPTION
**Pull request by mfazekas**
- Add RNMapboxMapsImpl to expo plugin (iOS only for now)
- Add prebuilt expo plugin to GitHub so it can be used from GitHub
- Add expo build compile to `yarn generate`

### CODE REVIEW

**Comment by jbreuer95** [comment]
Wow nice!, this would allow me to use the V10 branch in my production expo app and for me to switch to MapLibre. Can't wait for a merge :D

**Comment by jbreuer95** [comment]
@mfazekas  When i try this branch on EAS build i do get this:

```
An error occurred while processing the pre-install hook of the Podfile.
undefined method `pre_install' for nil:NilClass
```

This is my config:
```
    plugins: [
      [
        '@rnmapbox/maps',
        {
          RNMapboxMapsImpl: 'maplibre',
        },
      ]
    ],
```

**Comment by mfazekas** [comment]
@jbreuer95 can you try with main?! It's iOS only for now.
If you still see the issue, can you send the generated `ios/Podfile`?!

**Comment by jbreuer95** [comment]
@mfazekas Same error, i'm trying to borrow a macbook so i can eject since i don't own one and you cannot download the ios/Podfile of a failed EAS build.

**Comment by jbreuer95** [comment]
@mfazekas I think i found the problem, expo prebuild worked fine on an Macbook, the pre/post install hooks are there. Only autolinking seems te be broken when building with EAS, maybe EAS cannot install from Github instead of NPM.  Here is the full log of the pod install step:

```
Installing pods
Using Expo modules
Auto-linking React Native modules for target `DEV`: RNCPicker, RNGestureHandler, RNReanimated, RNSVG, RNScreens, react-native-mmkv, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
CocoaPods 1.11.3 is available.
To update use: `sudo gem install cocoapods`
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.3
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing EXApplication (4.0.2)
Installing EXConstants (13.0.2)
Installing EXErrorRecovery (3.0.5)
Installing EXFileSystem (13.1.4)
Installing EXFont (10.0.5)
Installing EXJSONUtils (0.2.1)
Installing EXKeepAwake (10.0.2)
Installing EXManifests (0.2.4)
Installing EXSplashScreen (0.14.2)
Installing EXUpdatesInterface (0.5.1)
Installing EXWebBrowser (10.1.1)
Installing Expo (44.0.6)
Installing ExpoModulesCore (0.6.5)
Installing ExpoSystemUI (1.1.1)
Installing FBLazyVector (0.64.3)
Installing FBReactNativeSpec (0.64.3)
Installing MMKV (1.2.13)
Installing MMKVCore (1.2.13)
Installing RCT-Folly (2020.01.13.00)
Installing RCTRequired (0.64.3)
Installing RCTTypeSafety (0.64.3)
Installing RNCPicker (2.2.1)
Installing RNGestureHandler (2.1.3)
Installing RNReanimated (2.3.3)
Installing RNSVG (12.1.1)
Installing RNScreens (3.10.2)
Installing React (0.64.3)
Installing React-Core (0.64.3)
Installing React-CoreModules (0.64.3)
Installing React-RCTActionSheet (0.64.3)
Installing React-RCTAnimation (0.64.3)
Installing React-RCTBlob (0.64.3)
Installing React-RCTImage (0.64.3)
Installing React-RCTLinking (0.64.3)
Installing React-RCTNetwork (0.64.3)
Installing React-RCTSettings (0.64.3)
Installing React-RCTText (0.64.3)
Installing React-RCTVibration (0.64.3)
Installing React-callinvoker (0.64.3)
Installing React-cxxreact (0.64.3)
Installing React-jsi (0.64.3)
Installing React-jsiexecutor (0.64.3)
Installing React-jsinspector (0.64.3)
Installing React-perflogger (0.64.3)
Installing React-runtimeexecutor (0.64.3)
Installing ReactCommon (0.64.3)
Installing Yoga (1.14.0)
Installing boost-for-react-native (1.63.0)
Installing expo-dev-client (0.8.4)
Installing expo-dev-launcher (0.10.4)
Installing expo-dev-menu (0.9.3)
Installing expo-dev-menu-interface (0.5.3)
Installing glog (0.3.5)
Installing hermes-engine (0.7.2)
Installing libevent (2.1.12)
Installing react-native-mmkv (2.1.0)
Installing react-native-safe-area-context (3.3.2)
[!] An error occurred while processing the pre-install hook of the Podfile.
undefined method `pre_install' for nil:NilClass
/Users/expo/workingdir/build/ios/Podfile:22:in `block (3 levels) in from_ruby'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/podfile.rb:162:in `pre_install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:869:in `run_podfile_pre_install_hook'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:857:in `block in run_podfile_pre_install_hooks'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:856:in `run_podfile_pre_install_hooks'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:254:in `block in download_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:252:in `download_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:161:in `install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:23:in `<main>'
[stderr] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `973F0C08384742B6B7916A4D` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
pod exited with non-zero code: 1
```

**Comment by mfazekas** [comment]
@jbreuer95 I've tried this:

```sh
expo init expo-rnmapbox
cd expo-rnmapbox
expo install rnmapbox/maps#main
# add to app.json under `expo/plugins`
#    "plugins": [
#      [ "@rnmapbox/maps",
#        {
#          "RNMapboxMapsImpl" : "maplibre"
#        }
#      ]
#    ]
# add eas.json
#    "simulator": {
#      "ios": {
#        "simulator": true
#      }
#    },
eas build --platform ios --local --profile simulator
```

Also can you do a 
```
grep -r RNM ./node_modules/@rnmapbox/maps/plugin/build
```

So I can confirm it's running with current state of `#main` branch

**Comment by jbreuer95** [comment]
@mfazekas Yes the plugin is working like it should, only somehow autolinking stops working when using the EAS (remote) build service.

I can see by the peer warning that the package does get installed and that the plugin is registered. Only it is missing from autolinking. I tried NPM as wel as Yarn. Also tried downgrading to 8.6.0 (that does work). 

```
Auto-linking React Native modules for target `DEV`: RNCPicker, RNGestureHandler, RNReanimated, RNSVG, RNScreens, react-native-mmkv, and react-native-safe-area-context
```

**Comment by mfazekas** [comment]
@jbreuer95 I'm not sure what's going on. 

If I do
```
EAS_LOCAL_BUILD_SKIP_CLEANUP=1 eas build --platform ios --local --profile simulator
```

then it shows what's using in the  the local build.

```
grep RNM /var/folders/zl/25rxtszd555clv8b9mbmhm0c0000gn/T/eas-build-local-nodejs/48a843f2-ccb1-456b-b538-614b6a3655c2/build/node_modules/@rnmapbox/maps/plugin/src/withMapbox.ts 
    newSrc: `    $RNMBGL.${blockName}_install(installer)`,
```

But the node_module of the project shows different stuff
```
boga@192 expo-rnmapbox % grep RNM node_modules/@rnmapbox/maps/plugin/src/withMapbox.ts 
  RNMapboxMapsImpl?: string;
  {RNMapboxMapsImpl},
        applyCocoaPodsModifications(contents, {RNMapboxMapsImpl}),
```

So somehow eas can end up using different version of GitHub. 
Instead of `#main` you can try using `#40eff47009a342948fea294968828fad745397ff`  maybe that forces an update

**Comment by jbreuer95** [comment]
@mfazekas Trying now, I do know EAS uses a npm cache server to speed up builds, so it could be installing an outdated #main version. Lets hope this works :D

**Comment by jbreuer95** [comment]
@mfazekas No luck, i keep getting `undefined method `pre_install' for nil:NilClass`

Can you increase the package.json version number in your branch from `10.0.0-beta.0` to `10.0.0-beta.1`?
Maybe it uses that key for caching.

**Comment by jbreuer95** [comment]
@mfazekas Sorry for the spam but i am fairly certain is has something to do with autolinking.

When i try this after a expo prebuild on the old 8.6.0 repo
```
npx react-native link @react-native-mapbox-gl/maps
```
I get a new line in the Podfile

When i try this
```
npx react-native link @rnmapbox/maps
```
I get no new line

**Comment by kristfal** [comment]
Just FYI, tested this over the weekend. Latest master needs manually added link in podfile still. 

This was on a project that was upgraded from the old package name, so could be related to that though.

**Comment by jbreuer95** [comment]
@kristfal I was just thinking the same thing! The version is not used in source defined the podspec
