### ISSUE TITLE
[Bug]: Typescript conversions fails to compile (ShapeSource, PointAnnotation)

### ISSUE THREAD

**Issue by mvniekerk** [rnmapbox/maps#2264]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

#main

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
 PointAnnotation,
 ShapeSource
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

It doesn't compile because the files aren't Typescript.

### Expected behavior

It compiles

### Notes / preliminary analysis

Provided Typescript files are not compiling

### Additional links and references

None

**Comment by mvniekerk** [comment]
Last compiling version was 10 beta 39

**Comment by mfazekas** [comment]
@mvniekerk can you also add the error you're seeing

**Comment by mfazekas** [comment]
For me this compiles:

```typescript
import { Geometry } from 'geojson';

const aLine: Geometry = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};
```

Full sample:
```typescript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
 PointAnnotation,
 ShapeSource
} from '@rnmapbox/maps';
import { Geometry } from 'geojson';

const aLine: Geometry = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

**Comment by BubbleTrouble14** [comment]
I get this error: SyntaxError: C:\Users\ronal\Documents\Programming\react-native\MobilizeReporting\node_modules\@rnmapbox\maps\javascript\components\PointAnnotation.tsx: Unexpected token (122:43)

  120 |  */
  121 | class PointAnnotation extends NativeBridgeComponent(
> 122 |   React.PureComponent<PointAnnotationProps>,
      |                                            ^
  123 |   NATIVE_MODULE_NAME,
  124 | ) {
  125 |   static defaultProps = {

**Comment by mvniekerk** [comment]
Sorry for the late reply @mfazekas , but what @BubbleTrouble14  has commented here https://github.com/rnmapbox/maps/issues/2264#issuecomment-1264677251

**Comment by mfazekas** [comment]
@mvniekerk @BubbleTrouble14  and what is the command you're running?!

**Comment by BubbleTrouble14** [comment]
I just start the app and get the error, after removing all imports from mapbox it works.

**Comment by mvniekerk** [comment]
If you open the TSX files in Intellij it even errors out there as well.
It breaks at compiler level - the files aren't valid Typescript.

Groete / Best regards
Michael van Niekerk
________________________________
Van: Ronald Goedeke ***@***.***>
Gestuur: Sunday, October 2, 2022 10:05:00 PM
aan: rnmapbox/maps ***@***.***>
Aa: Michael van Niekerk ***@***.***>; Mention ***@***.***>
onderwerp: Re: [rnmapbox/maps] [Bug]: Typescript conversions fails to compile (ShapeSource, PointAnnotation) (Issue #2264)


I just start the app and get the error, after removing all imports from mapbox it works.

**Comment by KiwiKilian** [comment]
First TS error occured in our project with 43, 44 adds another one. Simply upgrading the depencenies and running `tsc --noemit` triggers the following errors:

```
> tsc --noemit
node_modules/@rnmapbox/maps/javascript/components/AbstractLayer.tsx(65,61): error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'AllLayerStyleProps'.
node_modules/@rnmapbox/maps/javascript/components/NativeBridgeComponent.tsx(92,23): error TS2352: Conversion of type '(value: ReturnType | PromiseLike<ReturnType>) => void' to type '(args: NativeArg) => void' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of parameters 'value' and 'args' are incompatible.
    Type 'NativeArg' is not comparable to type 'ReturnType | PromiseLike<ReturnType>'.
      Type 'NativeArg[]' is not comparable to type 'ReturnType | PromiseLike<ReturnType>'.
        Type 'NativeArg[]' is not comparable to type 'ReturnType'.
          'ReturnType' could be instantiated with an arbitrary type which could be unrelated to 'NativeArg[]'.
```

It's an Expo project using this `tsconfig.json`:
```json
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true
  }
}
```

The behavior is somewhat similar to #2187. I can only reproduce in our project, no way to trigger these errors directly in `@rnmapbox/maps`.

**Comment by mfazekas** [comment]
Sorry not enough detail to reproduce

**Comment by allthetime** [comment]
Having the same issue. I just upgraded my packages from an old mapbox-gl version where everything in my app was running fine. Now I get this error upon opening the app. I removed all Mapbox components but kept the import and am still getting the error. 

```
SyntaxError: ....../app/node_modules/@rnmapbox/maps/javascript/components/ShapeSource.tsx: Unexpected token (158:36)

  156 |  */
  157 | export class ShapeSource extends NativeBridgeComponent(
> 158 |   AbstractSource<Props, NativeProps>,
      |                                     ^
  159 |   NATIVE_MODULE_NAME,
  160 | ) {
  161 |   static NATIVE_ASSETS_KEY = 'assets';

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
```

This is an error in library code, not my code.

**Comment by mvniekerk** [comment]
You have the files that is failing and you have tsc, why close the ticket @mfazekas?

**Comment by BubbleTrouble14** [comment]
Yes exactly the same for me. I created whole new project from scratch to test if I can get it to work. Works fine. But still havent figured out where the difference is to my existing project to fix the problem. Deleted node modules, cleaned project, rebuilt...

**Comment by allthetime** [comment]
Also, I just tested by removing the type annotations from ShapeSource and PointAnnotation like this:

![Screen Shot 2022-10-04 at 9 43 03 AM](https://user-images.githubusercontent.com/6376965/193878394-23a14641-7281-48d9-86c6-2c4b1e558d3d.png

to

![Screen Shot 2022-10-04 at 9 43 11 AM](https://user-images.githubusercontent.com/6376965/193878402-0ec26a05-e15d-4d9d-995f-cbb15c7b7306.png)
)

And now my app works again.

**Comment by BubbleTrouble14** [comment]
I'll give it a go, thx.

**Comment by mfazekas** [comment]
@BubbleTrouble14 maybe you have and old typescript version in your project, can you tell me which typescript are you using from the pacakge-lock or yarn.lock file?!

**Comment by allthetime** [comment]
@mfazekas what version should we be on for it to work?

**Comment by BubbleTrouble14** [comment]
> @BubbleTrouble14 maybe you have and old typescript version in your project, can you tell me which typescript are you using from the pacakge-lock or yarn.lock file?!

How does one search for it ?

**Comment by BubbleTrouble14** [comment]
Found it. Says:   "version": "4.6.4"

**Comment by allthetime** [comment]
Updated to latest (4.8.4), same problem.

Removing type annotations from PointAnnotation and ShapeSource like this fixed it for me:

![Screen Shot 2022-10-04 at 10 37 20 AM](https://user-images.githubusercontent.com/6376965/193888328-4439e1c3-6045-4543-852a-38dfe20a6653.png)

to 

![Screen Shot 2022-10-04 at 10 37 23 AM](https://user-images.githubusercontent.com/6376965/193888346-6df3663b-8bf5-4475-bbeb-f8495a04f9e2.png)

**Comment by KiwiKilian** [comment]
@allthetime did you check you are actually using 4.8.4 after your upgrade? Try running `npx tsc --version`. Our project uses `typescript@4.8.4`, only if I downgrade to 4.6.4 I can reproduce you problem.

**Comment by jrobber** [comment]
@KiwiKilian I'm not who you referenced, but here is a log after updating from v8 to v10 of my app:

```
❯ pnpm tsc --version
Version 4.8.4
❯ pnpm tsc
node_modules/@rnmapbox/maps/javascript/components/AbstractLayer.tsx:51:3 - error TS7030: Not all code paths return a value.

51   getStyleTypeFormatter(styleType: string) {
     ~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/components/Atmosphere.tsx:25:7 - error TS2322: Type 'ComponentType<any>' is not assignable to type 'HostComponent<{ reactStyle?: { [key: string]: StyleValue; }; style?: undefined; }>'.
  Type 'ComponentClass<any, any>' is not assignable to type 'HostComponent<{ reactStyle?: { [key: string]: StyleValue; }; style?: undefined; }>'.
    Type 'Component<any, any, any>' is not assignable to type 'Component<{ reactStyle?: { [key: string]: StyleValue; }; style?: undefined; }, {}, any> & Readonly<NativeMethods>'.
      Type 'Component<any, any, any>' is not assignable to type 'Readonly<NativeMethods>'.

25 const RCTMGLAtmosphere: HostComponent<{
         ~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/components/Camera.tsx:237:9 - error TS6133: 'triggerKey' is declared but its value is never read.

237         triggerKey,
            ~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/components/MarkerView.tsx:149:7 - error TS2322: Type 'ComponentType<any>' is not assignable to type 'HostComponent<NativeProps>'.
  Type 'ComponentClass<any, any>' is not assignable to type 'HostComponent<NativeProps>'.
    Type 'Component<any, any, any>' is not assignable to type 'Component<NativeProps, {}, any> & Readonly<NativeMethods>'.
      Type 'Component<any, any, any>' is not assignable to type 'Readonly<NativeMethods>'.

149 const RCTMGLMarkerView: HostComponent<NativeProps> =
          ~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/components/PointAnnotation.tsx:229:7 - error TS2322: Type 'ComponentType<any>' is not assignable to type 'NativePointAnnotation'.
  Type 'ComponentClass<any, any>' is not assignable to type 'HostComponent<NativePointAnnotationProps>'.
    Type 'Component<any, any, any>' is not assignable to type 'Component<NativePointAnnotationProps, {}, any> & Readonly<NativeMethods>'.
      Type 'Component<any, any, any>' is missing the following properties from type 'Readonly<NativeMethods>': measure, measureInWindow, measureLayout, setNativeProps, and 2 more.

229 const RCTMGLPointAnnotation: NativePointAnnotation =
          ~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/components/ShapeSource.tsx:333:7 - error TS7030: Not all code paths return a value.

333       return;
          ~~~~~~~

node_modules/@rnmapbox/maps/javascript/components/ShapeSource.tsx:411:7 - error TS2322: Type 'ComponentType<any>' is not assignable to type 'NativeShapeSource'.
  Type 'ComponentClass<any, any>' is not assignable to type 'HostComponent<NativeProps>'.
    Type 'Component<any, any, any>' is not assignable to type 'Component<NativeProps, {}, any> & Readonly<NativeMethods>'.
      Type 'Component<any, any, any>' is not assignable to type 'Readonly<NativeMethods>'.

411 const RCTMGLShapeSource: NativeShapeSource =
          ~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/requestAndroidLocationPermissions.ts:1:1 - error TS6133: 'number' is declared but its value is never read.

1 import { number } from 'prop-types';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:140:6 - error TS6196: 'FillTranslateAnchorEnum' is declared but never used.

140 enum FillTranslateAnchorEnum {
         ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:146:6 - error TS6196: 'FillTranslateAnchorEnumValues' is declared but never used.

146 type FillTranslateAnchorEnumValues = 'map' | 'viewport';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:165:6 - error TS6196: 'LineTranslateAnchorEnum' is declared but never used.

165 enum LineTranslateAnchorEnum {
         ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:171:6 - error TS6196: 'LineTranslateAnchorEnumValues' is declared but never used.

171 type LineTranslateAnchorEnumValues = 'map' | 'viewport';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:354:6 - error TS6196: 'IconTranslateAnchorEnum' is declared but never used.

354 enum IconTranslateAnchorEnum {
         ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:360:6 - error TS6196: 'IconTranslateAnchorEnumValues' is declared but never used.

360 type IconTranslateAnchorEnumValues = 'map' | 'viewport';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:361:6 - error TS6196: 'TextTranslateAnchorEnum' is declared but never used.

361 enum TextTranslateAnchorEnum {
         ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:367:6 - error TS6196: 'TextTranslateAnchorEnumValues' is declared but never used.

367 type TextTranslateAnchorEnumValues = 'map' | 'viewport';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:368:6 - error TS6196: 'CircleTranslateAnchorEnum' is declared but never used.

368 enum CircleTranslateAnchorEnum {
         ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:374:6 - error TS6196: 'CircleTranslateAnchorEnumValues' is declared but never used.

374 type CircleTranslateAnchorEnumValues = 'map' | 'viewport';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:389:6 - error TS6196: 'FillExtrusionTranslateAnchorEnum' is declared but never used.

389 enum FillExtrusionTranslateAnchorEnum {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:395:6 - error TS6196: 'FillExtrusionTranslateAnchorEnumValues' is declared but never used.

395 type FillExtrusionTranslateAnchorEnumValues = 'map' | 'viewport';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/StyleValue.ts:3:3 - error TS6133: 'ImageResolvedAssetSource' is declared but its value is never read.

3   ImageResolvedAssetSource,
    ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/StyleValue.ts:5:3 - error TS6133: 'ProcessedColorValue' is declared but its value is never read.

5   ProcessedColorValue,
    ~~~~~~~~~~~~~~~~~~~

node_modules/@rnmapbox/maps/javascript/utils/StyleValue.ts:24:5 - error TS7030: Not all code paths return a value.

24     return;
       ~~~~~~~


Found 23 errors in 9 files.

Errors  Files
     1  node_modules/@rnmapbox/maps/javascript/components/AbstractLayer.tsx:51
     1  node_modules/@rnmapbox/maps/javascript/components/Atmosphere.tsx:25
     1  node_modules/@rnmapbox/maps/javascript/components/Camera.tsx:237
     1  node_modules/@rnmapbox/maps/javascript/components/MarkerView.tsx:149
     1  node_modules/@rnmapbox/maps/javascript/components/PointAnnotation.tsx:229
     2  node_modules/@rnmapbox/maps/javascript/components/ShapeSource.tsx:333
     1  node_modules/@rnmapbox/maps/javascript/requestAndroidLocationPermissions.ts:1
    12  node_modules/@rnmapbox/maps/javascript/utils/MapboxStyles.ts:140
     3  node_modules/@rnmapbox/maps/javascript/utils/StyleValue.ts:3
```

**Comment by huszzsolt** [comment]
We are getting the same error.
![Screenshot 2022-12-23 at 14 55 03](https://user-images.githubusercontent.com/28455856/209339825-0ee0e7ce-9171-41b5-a572-64401e93967d.png)

I wonder it is because we are on a newer react:
    "react": "18.1.0",
(   "react-native": "0.70.6",)

Problem is present in the latest:  "@rnmapbox/maps": "v10.0.0-beta.61",

but works if I downgrade to   "@rnmapbox/maps": "v10.0.0-beta.28"

**Comment by allthetime** [comment]
@huszzsolt as a short term fix I recommend self-patching and using `patch-package`

1. Remove the type annotation. There is one other file this will happen in once you fix PointAnnotation (I forget what it is)

simply remove `<Props>`

2. run `npx patch-package`

I was having this issue before, but am not anymore, but I'm not sure what I did. I'm using the latest version of `rnmapbox/maps` but I'm on a slightly older `react-native 0.67.x`

Also, I'm on `"typescript": "^4.8.4"`

Might want to check your typescript version.

**Comment by chrisivo** [comment]
Have managed to get `@rnmapbox/maps@10.0.0-beta.62` working past the Typescript errors without needing a patch. Had the correct Typescript version installed. What set alarm bells of was that that the IDE complained about errors when I made the code adjustments suggested by @allthetime, but Babel obviously couldn't translate the Typescript without the adjustments present - so something was out of sync.

Problem (I think) has been corrected by updating my `@babel/core` and `@babel/runtime` npm's to match those  in the the `package.json` for this repo at present -

`yarn upgrade @babel/core@7.19.1`

`yarn upgrade @babel/runtime@7.19.0`

After this, in my case, I also needed to install `@babel/preset-env`, as Babel reported missing required plugins on build (all present in `present-env` apparently).

`yarn add @babel/preset-env --dev`

Have different issues to deal with now, so not out the woods yet! But HTH.

**Comment by viswakarmalovekush** [comment]
Hi @mfazekas what should I have to do in my case?

**Comment by Stophface** [comment]
@chrisivo I am freaking out here... I have been working on this for quite a while, but I cannot get it to work. I am getting the same error you mentioned

`error: node_modules/@rnmapbox/maps/javascript/components/ShapeSource.tsx: /xxxxx/node_modules/@rnmapbox/maps/javascript/components/ShapeSource.tsx: Unknown node type: "TSInstantiationExpression"`

But I cannot solve it. This are my `@babel` settings taken from mz projects `package.json`

```
    "@babel/core": "7.19.1",
    "@babel/plugin-proposal-decorators": "^7.17.9",
    "@babel/preset-env": "7.19.1",
    "@babel/preset-typescript": "^7.18.6",
    "@babel/runtime": "7.19.0",
```

This is the `babel.config.js`

```
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
    '@babel/preset-typescript',
  ],
  plugins: [
    'react-native-reanimated/plugin',
    ['@babel/plugin-proposal-decorators', {legacy: true}],
  ],
};
```

and this is from the `package.json`  of `@rnmapbox/maps`

```
    "@babel/core": "7.19.1",
    "@babel/eslint-parser": "^7.19.1",
    "@babel/plugin-proposal-class-properties": "7.18.6",
    "@babel/runtime": "7.19.0",
```

Do you have a hint why I am still seeing this error?

**Comment by RuzenDev** [comment]
Me too , am having similar error but in my case its, VectorSource.tsx. 

error: node_modules/@rnmapbox/maps/src/components/VectorSource.tsx: /Users/node_modules/@rnmapbox/maps/src/components/VectorSource.tsx: Unknown node type: "TSInstantiationExpression"

**Comment by RuzenDev** [comment]
@Stophface HI!, Did you solve it?
