### ISSUE TITLE
[Bug]: Android crash using UserLocation

### ISSUE THREAD

**Issue by kvntzn** [rnmapbox/maps#3799]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### React Native Version

0.76.7

### Platform

Android

### `@rnmapbox/maps` version

10.1.37

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  UserLocation,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class App extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera />
        <UserLocation />
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

- Android crash on Open

```
2025-03-05 10:49:47.080 19824-19824 AndroidRuntime          com.passenger          E  FATAL EXCEPTION: main
                                                                                                    Process: com.passenger, PID: 19824
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.bridge.CxxCallbackImpl.invoke(java.lang.Object[])' on a null object reference
                                                                                                    	at com.rnmapbox.rnmbx.NativeRNMBXLocationModuleSpec.emitOnLocationUpdate(NativeRNMBXLocationModuleSpec.java:38)
                                                                                                    	at com.rnmapbox.rnmbx.modules.RNMBXLocationModule.access$emitOnLocationUpdate(RNMBXLocationModule.kt:18)
                                                                                                    	at com.rnmapbox.rnmbx.modules.RNMBXLocationModule$onUserLocationChangeCallback$1.onLocationChange(RNMBXLocationModule.kt:62)
                                                                                                    	at com.rnmapbox.rnmbx.location.LocationManager.onLocationChanged(LocationManager.kt:251)
                                                                                                    	at com.rnmapbox.rnmbx.location.LocationManager.onSuccess(LocationManager.kt:260)
                                                                                                    	at com.rnmapbox.rnmbx.location.LocationManager.onSuccess(LocationManager.kt:93)
                                                                                                    	at com.mapbox.android.core.location.LocationEngineCommonCompatKt$toCommonCompat$1.onSuccess(LocationEngineCommonCompat.kt:99)
                                                                                                    	at com.mapbox.android.core.location.LocationEngineCommonCompatKt$toCommonCompat$1.onSuccess(LocationEngineCommonCompat.kt:93)
                                                                                                    	at com.mapbox.common.location.compat.LocationEngineImpl$liveTrackingObserver$1$onLocationUpdateReceived$lambda-2$lambda-1$$inlined$postOrCall$1.run(LocationEngineImpl.kt:361)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)```

### Expected behavior

_No response_

### Notes / preliminary analysis

_No response_

### Additional links and references

_No response_

**Comment by kvntzn** [comment]
> ### Mapbox Implementation
> Mapbox
> 
> ### Mapbox Version
> default
> 
> ### React Native Version
> 0.76.7
> 
> ### Platform
> Android
> 
> ### `@rnmapbox/maps` version
> 10.1.37
> 
> ### Standalone component to reproduce
> import React from 'react';
> import {
>   MapView,
>   ShapeSource,
>   LineLayer,
>   UserLocation,
>   Camera,
> } from '@rnmapbox/maps';
> 
> const aLine = {
>   type: 'LineString',
>   coordinates: [
>     [-74.00597, 40.71427],
>     [-74.00697, 40.71527],
>   ],
> };
> 
> class App extends React.Component {
>   render() {
>     return (
>       <MapView style={{flex: 1}}>
>         <Camera />
>         <UserLocation />
>       </MapView>
>     );
>   }
> }
> ### Observed behavior and steps to reproduce
> * Android crash on Open
> 
> ```
> 2025-03-05 10:49:47.080 19824-19824 AndroidRuntime          com.passenger          E  FATAL EXCEPTION: main
>                                                                                                     Process: com.passenger, PID: 19824
>                                                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.bridge.CxxCallbackImpl.invoke(java.lang.Object[])' on a null object reference
>                                                                                                     	at com.rnmapbox.rnmbx.NativeRNMBXLocationModuleSpec.emitOnLocationUpdate(NativeRNMBXLocationModuleSpec.java:38)
>                                                                                                     	at com.rnmapbox.rnmbx.modules.RNMBXLocationModule.access$emitOnLocationUpdate(RNMBXLocationModule.kt:18)
>                                                                                                     	at com.rnmapbox.rnmbx.modules.RNMBXLocationModule$onUserLocationChangeCallback$1.onLocationChange(RNMBXLocationModule.kt:62)
>                                                                                                     	at com.rnmapbox.rnmbx.location.LocationManager.onLocationChanged(LocationManager.kt:251)
>                                                                                                     	at com.rnmapbox.rnmbx.location.LocationManager.onSuccess(LocationManager.kt:260)
>                                                                                                     	at com.rnmapbox.rnmbx.location.LocationManager.onSuccess(LocationManager.kt:93)
>                                                                                                     	at com.mapbox.android.core.location.LocationEngineCommonCompatKt$toCommonCompat$1.onSuccess(LocationEngineCommonCompat.kt:99)
>                                                                                                     	at com.mapbox.android.core.location.LocationEngineCommonCompatKt$toCommonCompat$1.onSuccess(LocationEngineCommonCompat.kt:93)
>                                                                                                     	at com.mapbox.common.location.compat.LocationEngineImpl$liveTrackingObserver$1$onLocationUpdateReceived$lambda-2$lambda-1$$inlined$postOrCall$1.run(LocationEngineImpl.kt:361)
>                                                                                                     	at android.os.Handler.handleCallback(Handler.java:959)
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:100)
>                                                                                                     	at android.os.Looper.loopOnce(Looper.java:232)
>                                                                                                     	at android.os.Looper.loop(Looper.java:317)
>                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8705)
>                                                                                                     	at java.lang.reflect.Method.invoke(Native Method)
>                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
>                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)```
> 
> ### Expected behavior
> 
> _No response_
> 
> ### Notes / preliminary analysis
> 
> _No response_
> 
> ### Additional links and references
> 
> _No response_
> ```

**Comment by anandtatva** [comment]
> > ### Mapbox Implementation
> > Mapbox
> > ### Mapbox Version
> > default
> > ### React Native Version
> > 0.76.7
> > ### Platform
> > Android
> > ### `@rnmapbox/maps` version
> > 10.1.37
> > ### Standalone component to reproduce
> > import React from 'react';
> > import {
> > MapView,
> > ShapeSource,
> > LineLayer,
> > UserLocation,
> > Camera,
> > } from '@rnmapbox/maps';
> > const aLine = {
> > type: 'LineString',
> > coordinates: [
> > [-74.00597, 40.71427],
> > [-74.00697, 40.71527],
> > ],
> > };
> > class App extends React.Component {
> > render() {
> > return (
> > <MapView style={{flex: 1}}>
> > 
> > 
> > 
> > );
> > }
> > }
> > ### Observed behavior and steps to reproduce
> > 
> > * Android crash on Open
> > 
> > ```
> > 2025-03-05 10:49:47.080 19824-19824 AndroidRuntime          com.passenger          E  FATAL EXCEPTION: main
> >                                                                                                     Process: com.passenger, PID: 19824
> >                                                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.bridge.CxxCallbackImpl.invoke(java.lang.Object[])' on a null object reference
> >                                                                                                     	at com.rnmapbox.rnmbx.NativeRNMBXLocationModuleSpec.emitOnLocationUpdate(NativeRNMBXLocationModuleSpec.java:38)
> >                                                                                                     	at com.rnmapbox.rnmbx.modules.RNMBXLocationModule.access$emitOnLocationUpdate(RNMBXLocationModule.kt:18)
> >                                                                                                     	at com.rnmapbox.rnmbx.modules.RNMBXLocationModule$onUserLocationChangeCallback$1.onLocationChange(RNMBXLocationModule.kt:62)
> >                                                                                                     	at com.rnmapbox.rnmbx.location.LocationManager.onLocationChanged(LocationManager.kt:251)
> >                                                                                                     	at com.rnmapbox.rnmbx.location.LocationManager.onSuccess(LocationManager.kt:260)
> >                                                                                                     	at com.rnmapbox.rnmbx.location.LocationManager.onSuccess(LocationManager.kt:93)
> >                                                                                                     	at com.mapbox.android.core.location.LocationEngineCommonCompatKt$toCommonCompat$1.onSuccess(LocationEngineCommonCompat.kt:99)
> >                                                                                                     	at com.mapbox.android.core.location.LocationEngineCommonCompatKt$toCommonCompat$1.onSuccess(LocationEngineCommonCompat.kt:93)
> >                                                                                                     	at com.mapbox.common.location.compat.LocationEngineImpl$liveTrackingObserver$1$onLocationUpdateReceived$lambda-2$lambda-1$$inlined$postOrCall$1.run(LocationEngineImpl.kt:361)
> >                                                                                                     	at android.os.Handler.handleCallback(Handler.java:959)
> >                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:100)
> >                                                                                                     	at android.os.Looper.loopOnce(Looper.java:232)
> >                                                                                                     	at android.os.Looper.loop(Looper.java:317)
> >                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8705)
> >                                                                                                     	at java.lang.reflect.Method.invoke(Native Method)
> >                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
> >                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)```
> > 
> > ### Expected behavior
> > 
> > _No response_
> > 
> > ### Notes / preliminary analysis
> > 
> > _No response_
> > 
> > ### Additional links and references
> > 
> > _No response_
> > ```

same error
any update

**Comment by illia-port** [comment]
FYI, downgrade to 10.1.36 seems to work

**Comment by Hosam-hsm** [comment]
Facing same issue. Any update on this?

**Comment by rakhim06** [comment]
Hello,

I was able to make it work with v10.1.37 with Expo.
If you have updated to SDK 52, please add in **app.config.js** :
```
[
    "expo-build-properties",
    {
        android: {
            newArchEnabled: true,
        },
        ios: {
            newArchEnabled: true,
        },
    },
],
```

source: https://docs.expo.dev/guides/new-architecture/

then run
`npx expo prebuild`
`npm run android`

**Comment by HamoBoker** [comment]
`@rnmapbox/maps v10.1.38`
`react-native v0.76.9`
`RNMapboxMapsVersion v11.9.2`

newArch: false

```zhs
ERROR  TypeError: MapboxGLLocationManager.onLocationUpdate is not a function (it is undefined), js engine: hermes
```

**Comment by achou11** [comment]
@kvntzn this seems to be a duplicate of https://github.com/rnmapbox/maps/issues/3796? If you can confirm that, maybe mark this issue as a duplicate for the sake of the maintainers.
